version: '3.8'

services:
  chip8_rom_server:
    build:
      context: ./chip8_rom_server
      dockerfile: Dockerfile
    container_name: chip8_rom_server
    env_file:
      - ./chip8_rom_server/.env
    ports:
      - "8080:8080"
    restart: unless-stopped
